repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
        name: "Check if commit is not directly to main branch"
        default_stages: [push]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        name: "Check if code is formatted"
        args: ["--check"]
- repo: local
  hooks:
    - id: pylint
      name: "Linter"
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "-d C0114", # Silence documentation warnings
          "-d C0115", # ?
          "-d C0116", # ?
          "-d C0209", # Silence consider-using-f-string
          "-d W0106", # Silence unassigned expression
          "-d E0213", # Silence no-self-argument
          "-d W0511", # Silence to do comments
          "-d R0903", # Silence too-few-public-methods
          "-d E0237", # Silence external attribute assignment
          "-d E0611" # Silence no-name-in-module
        ]
