repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: no-commit-to-branch
        name: "Check if commit is not directly to main branch"
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        name: "Check if code is formatted"
        args: ["--check"]
- repo: local
  hooks:
    - id: pylint
      name: "Linter"
      entry: pylint
      language: system
      types: [python]
      args:
        [
          "-rn", # Only display messages
          "-sn", # Don't display the score
        ]
