version: '3'
services:
  app:
    build: .
    volumes:
      - ./app:/app/app
    command: ["python3", "main.py"]
    env_file:
      - .env
    ports:
      - "8995:8995"
    container_name: musicbot
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: sql1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: discordbot
    ports:
      - "5432:5432"
