version: '3'
services:
  app:
    image: websoftdevs/musicbot:prod
    volumes:
      - ./app:/app/app
    command: ["python3", "main.py"]
    env_file:
      - .env
    ports:
      - "8001:8001"
    container_name: musicbot2
