version: '3'
services:
  pytest:
    build:
      context: .
      dockerfile: development/local/pytest/Dockerfile
    container_name: pytest
    env_file:
      - .env
    volumes:
      - ./coverage:/app/coverage
