name: ci-cd

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    name: ci-cd
    runs-on: ubuntu-latest
    steps:
      - name: ci-cd
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd MusicBot2
            sudo git pull
            sudo echo -e 'BOT_TOKEN=${{ secrets.BOT_TOKEN }}\nPREFIX=${{ secrets.PREFIX }}' | sudo tee MusicBot2/.env
            sudo docker build . %% sudo docker-compose -f docker-compose-prod.yml up -d
