name: release
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          sudo docker pull websoftdevs/musicbot:prod